name: MoreMaterials
version: 2.0
description: Custom blocks and items!
authors: [AlmuraDev, IceReaper, Znickq]
website: http://www.morematerials.net

depend: [Spout]
main: net.morematerials.MoreMaterials

commands:
  mm:
    description: Some basic commands!
    usage: /<command> [?]
  mmdebug:
    description: Show information about current material.
    usage: /<command>
  mmgive:
    description: Gives you a custom material.
    usage: /<command> [custom material] {amount}
    permission: morematerials.give

permissions:
  morematerials.*:
    description: Allows access to all of MoreMaterials' functionality.
    default: op
    children:
      morematerials.admin: true
      morematerials.craft: true
      morematerials.handlers.consume: true
  morematerials.admin:
    description: Access to commands.
    default: op
  morematerials.handlers.consume:
    description: allows user to utilize built-in consume handler.
    default: op
  morematerials.craft:
    description: Allows crafting of MoreMaterials blocks and items.
    default: true
